[workspace]
resolver = "2"
default-members = ["maxima-cli"]
members = [
    "maxima-bootstrap",
    "maxima-cli",
    "maxima-lib",
    "maxima-native",
    "maxima-service",
    "maxima-ui",
    "maxima-resources",
]

[profile.release]
strip = true
